### ISSUE TITLE
`sample/tutorial` examples do not work

### ISSUE THREAD

**Issue by guss77** [ruby-gnome2/ruby-gnome2#514]
Most examples in the tutorial fail with the error

    undefined method `run' for #<Gtk::Application:0x####### ptr=0x#######> (NoMethodError)

System: Ubuntu 15.04
Gem: gtk3 (2.2.5)

**Comment by cedlemo** [comment]
I guess it only works with the 2.2.6 version which is the devel version (it should be released soon if I well understood @kou ).

You should install it, it works well. These are the instructions in order to build/install (they are in the README.md too)

    % git clone https://github.com/ruby-gnome2/ruby-gnome2.git
    % cd ruby-gnome2
    % gem install rake rake-compiler mechanize pkg-config cairo
    % rake gem:install

**Comment by guss77** [comment]
I didn't manage to build the gems locally, but I'll open a different ticket for that.

**Comment by kou** [comment]
(I want to release new version soon but I'll be busy again soon... Oh...)
